
#Flight Info
org.akshay.flight.flightNumber=AI101
org.akshay.flight.departureCity=Delhi
org.akshay.flight.destinationCity=Mumbai
org.akshay.flight.ticketPrice=3500.00


org.akshay.user.userId=1
org.akshay.user.userName=Rahul Sharma

org.akshay.user.address.street=123 Main St
org.akshay.user.address.city=Mumbai
org.akshay.user.address.state=Maharashtra
org.akshay.user.address.zipCode=400001



