spring.application.name=BootProj07-UniversityManagementSystem-1


# University Properties
university.name=Sant Gadge Baba University
university.location=Amaravati
university.ranking=5

# Student Properties
student.name=Akshay Patil
student.age=27
student.major=Computer Science
student.year=Junior
